In [1]:
import numpy as np

# Question 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
arr = np.arange(2,51,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Question 2:
Accept two lists of 5 elements each from the user.

Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
l1 = [int(item) for item in input("Enter the list 1 items :").split()]
l2 = [int(item) for item in input("Enter the list 2 items :").split()] 
arr1 = np.array(l1)
arr2 = np.array(l2)
arr3 = np.concatenate([arr1,arr2])
print("\nNumpy Arr1:",arr1)
print("Numpy Arr2:",arr2)
print("\nConcatenation of the two Numpy Arrays:",arr3)
print("\nSorted Arr1:",np.sort(arr1))
print("Sorted Arr2:",np.sort(arr2))
print("Sorted Arr3:",np.sort(arr3))

Enter the list 1 items :5 4 3 2 1
Enter the list 2 items :10 9 8 7 6

Numpy Arr1: [5 4 3 2 1]
Numpy Arr2: [10  9  8  7  6]

Concatenation of the two Numpy Arrays: [ 5  4  3  2  1 10  9  8  7  6]

Sorted Arr1: [1 2 3 4 5]
Sorted Arr2: [ 6  7  8  9 10]
Sorted Arr3: [ 1  2  3  4  5  6  7  8  9 10]


# Question 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("No. of dimensions:", arr.ndim)
print("Size of array:", arr.size)

No. of dimensions: 2
Size of array: 9


# Question 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

Hint: np.newaxis, np.expand_dims

In [5]:
arr1 = np.array([1,2,3,4,5])
print("1D Array:",arr1)
print("Shape:",arr1.shape)
arr = np.expand_dims(arr1, axis=1)
print("\n2D Array:\n",arr)
print("Shape:",arr.shape)

1D Array: [1 2 3 4 5]
Shape: (5,)

2D Array:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Shape: (5, 1)


# Question 5:
Consider two square numpy arrays. Stack them vertically and horizontally.

Hint: Use vstack(), hstack()

In [6]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print("Vertical Stack:\n",np.vstack((arr1,arr2)))
print("Horizontal Stack:",np.hstack((arr1,arr2)))

Vertical Stack:
 [[1 2 3 4]
 [5 6 7 8]]
Horizontal Stack: [1 2 3 4 5 6 7 8]


# Question 6:
How to get unique items and counts of unique items?

In [7]:
arr = np.array([1,3,4,5,2,4,5,6,8,3,5,3,5,7,4,2])
unique_items, count_unique_items = np.unique(arr,return_counts=True)
print("Unique items:",unique_items)
print("Count of Unique items:",count_unique_items)

Unique items: [1 2 3 4 5 6 7 8]
Count of Unique items: [1 2 3 3 4 1 1 1]
